### ISSUE TITLE
Acho que não precisa ter HTML nos exemplos

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/patrimonio#12]
Da para deixar um exemplo mais simples e legível só com PHP mesmo.

**Comment by masakik** [comment]
Para o numpat não precisaria mesmo mas para o numpats tem o captcha que aí não tem muito jeito. Talvez colocar um exemplo em linha de comando também para complementar.

**Comment by girol** [comment]
Acho q esse exemplo poderia ser colocado na documentação e não em source code.
