### ISSUE TITLE
problema no composer

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/patrimonio#14]
`Warning: Ambiguous class resolution, "Uspdev\dadosUsp" was found in both "/home/thiago/repos/copaco/vendor/uspdev/patrimonio/src/dadosUsp.class.php" and "/home/thiago/repos/copaco/vendor/uspdev/patrimonio/src/dadosUsp_original.class.php", the first will be used.`

**Comment by masakik** [comment]
A gente precisa apagar esse arquivo antigo para não ter esse tipo de problema. Amanhã faço um cleanup.

**Comment by girol** [comment]
É só renomear a classe dentro do arquivo. Ou apaga de vez
