### ISSUE TITLE
Poderíamos ter um método ativo($numpat) qua verifica se o bem está ou não ativo (i.e. baixado), retornando true ou false apenas

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/patrimonio#19]

**Comment by masakik** [comment]
se não existir também retornaria false?

**Comment by masakik** [comment]
Quer dizer que se a situação não for Ativo retorna falso. Tem a possibilidade Baixado e Transferido. Não sei se tem outros.

**Comment by thiagogomesverissimo** [comment]
Não sei também. Então o método poderia ser situação: baixado, transferido, ativo etc

**Comment by masakik** [comment]
caso  típico foram os phoneip que vieram da reitoria, tinha patrimonio 001.xxx e contava transferido. Não sei como fica na unidade de destino que o que peguei na mão ainda estava com nro da reitoria.

**Comment by masakik** [comment]
Como o estado do bem tem várias possibilidades e não somente baixado e ativo mudei para Stabem e retorna exatamente essa variável dos dados usp. Ainda sim, se for o caso poderíamos incluir o método ativo que retorna true ou false
