### ISSUE TITLE
Adicionar método que verifica se o sistemas USP está no ar antes de enviar uma requisição 

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/patrimonio#22]
Pois ao executar implexml_load_string($e) em um objeto $e que não retonado resulta no erro: 
simplexml_load_string(): Entity: line 1: parser error : StartTag: invalid element name.
Uma solução que pense:

Antes de executar o método que faz a requisição curlPost() adicionar um outro método que verifica se o serviço tá no ar e em caso negativo, não fazer a requisição.

**Comment by masakik** [comment]
De fato tenho esse problema onde uso essa Lib.  Será que um get  na url pra ver se está no ar seria o suficiente?

**Comment by thiagogomesverissimo** [comment]
Eu ainda não consegui um jeito de pensar nessa checagem, mas por ora tive que desativar essa lib no copaco, pois o sistema estava ficando fora muito tempo:
https://github.com/uspdev/copaco/issues/361
https://github.com/uspdev/copaco/commit/37577f00d95e65275b8d027a5361abb4e0770d7b

**Comment by masakik** [comment]
fui verificar o problema e o servidor está entregando um xml mal formado.

    <Asidgtvd3></Asidgtvd3>
    <Stabemlibllo>	<Stabemlibllofmt></Stabemlibllofmt>
    <Estcsrbem>	<Staconutlbem></ai.patrimonio.PatrimonioBean>

Há algumas tags abertas que não são fechadas.

**Comment by masakik** [comment]
o xml foi corrigido mas o problema de checagem ainda não foi tratado.
