### ISSUE TITLE
Melhorar legibilidade de código

### ISSUE THREAD

**Issue by girol** [uspdev/patrimonio#4]
Nomear variáveis e métodos com nomes mais fáceis de ler.

**Comment by girol** [comment]
Decidir nomeação de métodos e classes em pt-br ou en-us majoritariamente.

**Comment by masakik** [comment]
haha, tenho misturado muito mesmo. Como é específico padronizar em em pt-br pode ser melhor

**Comment by masakik** [comment]
Acho que já deixei tudo em português, pelo menos o que consegui ver.
