### ISSUE TITLE
variáveis private em favor de global

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/patrimonio#9]
Caras, 
Eu usaria essa lógica:

```php
class dadosUsp
{

    private $c['numpat'] = array(
        'CURLOPT_URL' => "https://uspdigital.usp.br/mercurioweb/PatrimonioMostrar",
        'CURLOPT_REFERER' => "https://uspdigital.usp.br/mercurioweb/ainumpatimonio.jsp?codmnu=248",
        'naoexiste_str' => "Não existe Patrimônio nas condições especificadas!"
    );

    public function fetchNumpat($numpat)
    {
        $args = $this->c['numpat'];
    }
```

**Comment by thiagogomesverissimo** [comment]
Ou para não mudar muito sua classe e já a conseguimos a utilizar em outros projeto, podemos apenas dar um include do arquivo de configuração na classe.

**Comment by masakik** [comment]
E se colocar como variavel da classe mas com a possibilidade de sobrescrever passando parametro na instanciação?

**Comment by thiagogomesverissimo** [comment]
Acho q neste caso, essas variáveis não são variáveis, mas sim parâmetros, praticamente estáticos. Então, onerar a chamada dos métodos com valores que nunca mudam,.acho que vai deixar a classe não amigável.

**Comment by masakik** [comment]
Pode ser. Acho que poderia refatorar toda ela ajustando tudo o que precisar. Já que as pessoas ainda vão começar a usar.

**Comment by masakik** [comment]
Eram variáveis pois pelo menos umas 3x esses parâmetros mudaram e aí tive de ajustar para voltar a funcionar. Mas já fazem anos que não muda nada.

**Comment by thiagogomesverissimo** [comment]
Seu último PR resolve essa questão. Fechando issue.
